apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: tkmpge6v0-nodejs
  janus-idp.io/tekton: tkmpge6v0-nodejs
  backstage.io/kubernetes-id: tkmpge6v0-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tkmpge6v0-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
